# Generated by Django 3.0.14 on 2021-11-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
