# Generated by Django 3.0.14 on 2021-11-15 08:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211114_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Giờ tạo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Giờ cập nhật'),
        ),
    ]
